config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    # _form.html.erbで使用する変数を定義
    @task  = Task.new
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/tasks/_form.html.haml
= form_with(model: task, local: true) do |form|
  - if task.errors.any?
    #error_explanation
      %h2
        = pluralize(task.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - task.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    / idを付与
    = form.text_field :title, id: :task_title
  .actions
    / idを付与
    = form.submit "Submit", id: "submit"

app/views/tasks/edit.html.haml
%h1 Editing Task
= render 'form', task: @task
= link_to 'Show', @task
|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%p#notice= notice
%h1#title Tasks
/ scaffoldで自動生成したformを呼び出し
= render 'form', task: @task
%table
  %thead
    %tr
      %th Title
      %th{:colspan => "3"}
  / jQueryでDOMを取得できるようidを付与
  %tbody#task-list
    - @tasks.each do |task|
      %tr
        %td= task.title
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }
%br/

app/views/tasks/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @task.title
= link_to 'Edit', edit_task_path(@task)
|
= link_to 'Back', tasks_path